import 'package:cloud_firestore/cloud_firestore.dart';

class PlantScanModel {
  final String? plantId; // Generated by Firestore
  final String userId;
  final DateTime date;
  final String imageUrl;
  final String plantTypeId;
  final String plantIllnessId;
  final String? notes;
  final GeoPoint? location;

  PlantScanModel({
    this.plantId,
    required this.userId,
    required this.date,
    required this.imageUrl,
    required this.plantTypeId,
    required this.plantIllnessId,
    this.notes,
    this.location,
  });

  factory PlantScanModel.fromMap(Map<String, dynamic> data, String documentId) {
    return PlantScanModel(
      plantId: documentId,
      userId: data['userId'] ?? '',
      date: (data['date'] as Timestamp?)?.toDate() ?? DateTime.now(),
      imageUrl: data['imageUrl'] ?? '',
      plantTypeId: data['plantTypeId'] ?? '',
      plantIllnessId: data['plantIllnessId'] ?? '',
      notes: data['notes'],
      location: data['location'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'date': Timestamp.fromDate(date),
      'imageUrl': imageUrl,
      'plantTypeId': plantTypeId,
      'plantIllnessId': plantIllnessId,
      if (notes != null) 'notes': notes,
      if (location != null) 'location': location,
    };
  }
}
